### ISSUE TITLE
pip: Version 2.0 is not available

### ISSUE THREAD

**Issue by sethlivingston** [mailin-api/mailin-api-python#10]
The only version that is available to install via `pip` is 1.0. Downloading mailin.py or forking or cloning does not give us an easy way to keep up with new releases and fixes.

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We have updated https://pypi.python.org/pypi/Sendinblue/2.0
You can access API V2.0 now.

Regards,
SendinBlue Team

**Comment by sethlivingston** [comment]
When I run:

    sudo pip install Sendinblue==2.0.0

I get:

```
Downloading/unpacking Sendinblue==2.0.0
  Downloading Sendinblue-2.0.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/Sendinblue/setup.py) egg_info for package Sendinblue
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/Sendinblue/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/Sendinblue/setup.py'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/Sendinblue
Storing debug log for failure in /home/seth/.pip/pip.log
```

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We have updated our [Sendinblue PYPI](https://pypi.python.org/pypi/Sendinblue/) with object-based wrappers for Api version 2.0.
You can download it using below command

```
sudo pip install Sendinblue==2.0.2
```

**Note:** For this latest version, it is highly recommended to update way of sending input parameters.
Please refer new Python samples in [Apidoc](https://apidocs.sendinblue.com/).


Regards,
SendinBlue Team

**Comment by sethlivingston** [comment]
That worked. Thank you!
