### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by austin-bowen-advyon** [mailin-api/mailin-api-python#12]
I'd love to try SendinBlue, but there is no Python3 support.  When I try [the tutorial to send transactional email](https://apidocs.sendinblue.com/tutorial-sending-transactional-email/), I get this error:

```python
>>> m.send_email(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bwo/projects/bwo_api/lib/python3.4/site-packages/mailin.py", line 384, in send_email
    return self.post("email",json.dumps(data))
  File "/home/bwo/projects/bwo_api/lib/python3.4/site-packages/mailin.py", line 19, in post
    return self.do_request(resource,"POST",indata)
  File "/home/bwo/projects/bwo_api/lib/python3.4/site-packages/mailin.py", line 14, in do_request
    r,c = h.request(url,method,body=indata,headers={'api-key':self.api_key, 'content-type':content_type})   
  File "/home/bwo/projects/bwo_api/lib/python3.4/site-packages/httplib2/__init__.py", line 1196, in request
    self.disable_ssl_certificate_validation)
  File "/home/bwo/projects/bwo_api/lib/python3.4/site-packages/httplib2/__init__.py", line 850, in __init__
    check_hostname=True)
  File "/usr/lib/python3.4/http/client.py", line 1211, in __init__
    raise ValueError("check_hostname needs a SSL context with "
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

**Comment by ekta-slit** [comment]
Hello Austin,

Thank you for contacting us.

We are working on SendinBlue API V2.0 compatibility with Python3.
Once released, we will give updates.

Regards,
SendinBlue Team

**Comment by ekta-slit** [comment]
Hello Austin,

We appreciate your time & patience with us.
[API V2.0](https://github.com/mailin-api/mailin-api-python/tree/master/V2.0) is now compatible with Python3.

You can re-download the wrapper to continue the services.

Thank you,
SendinBlue Team

**Comment by toram** [comment]
Hello I've the same problem with this version (the last on github) on a local/dev machine. I dowloaded this version today.

ValueError at /bookings/cancel/54
check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
Request Method:	POST
Request URL:	http://127.0.0.1:8000/bookings/cancel/54
Django Version:	1.9.7
Exception Type:	ValueError
Exception Value:	
check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
Exception Location:	/usr/lib/python3.4/http/client.py in __init__, line 1211

Thanks,
Josep

**Comment by ekta-slit** [comment]
Hello,

The issue ``` Python ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED ``` is global between httplib2 & Python3.

We would recommend you to follow the fix as discussed here: https://groups.google.com/forum/#!topic/adwords-api/I2iVdUmzeac

Please take a look & give us your feedback on this!

Thank You
SendinBlue Team

**Comment by edvm** [comment]
I hit the same problem. Reading @ekta-slit last comment, and reading https://groups.google.com/forum/#!topic/adwords-api/I2iVdUmzeac i modified httplib2/__init__.py (which is horrible) as:
```check_hostname=True)

to this:
check_hostname=disable_ssl_certificate_validation ^ True)
```
And the Sendinblue API Key 2.0 works fine!
I had this problem using python 3.4 but didnt have this problem using python 3.5.1. So i think the best solution is, if you can, use python 3.5.1.or >
Best,
Emiliano.
