### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AGASS007** [mailin-api/mailin-api-python#15]
Hello,

could we get a new PyPI release with the latest changes (switch to **requests**).

Cheers

**Comment by bsvetchine** [comment]
+1 :)

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We have updated PyPI.
Here is the new release using requests module: https://pypi.python.org/pypi/Sendinblue/2.0.5.1


Regards,
SendinBlue Team

**Comment by AGASS007** [comment]
Hey,

thanks for the quick reply. I see you uploaded a 2.0.6 as well, what's the difference?

Cheers

**Comment by ekta-slit** [comment]
Hey @AGASS007 

Thanks for noticing, 2.0.6 is no longer available, please ignore :)

Regards
SendinBLue Team
