### ISSUE TITLE
Do not remove old versions from PyPI

### ISSUE THREAD

**Issue by 23doors** [mailin-api/mailin-api-python#16]
Why are you removing old versions of package from PyPI? That is incredibly frustrating for anyone using your packages. Not to mention, it's not a good practice. If something doesn't get completely deprecated or is found to be incredibly buggy - leave it alone. 

I see that you already did that a few times. Someone's frozen requirements set should not be forced to change on a whim and it's causing issues for anyone using your package on anything more serious.

**Comment by ekta-slit** [comment]
Hi @23doors 

Thank you for contacting us.
We appreciate your suggestions & will maintain all the upcoming versions of package.

Regards
SendinBlue Team.
