### ISSUE TITLE
Can't get send_email to work

### ISSUE THREAD

**Issue by jayanth1991** [mailin-api/mailin-api-python#17]
Hi, I've been trying to follow the docs for sending an email via the library, what the documentation says contradicts what the sample code is doing.

```py
    from mailin import Mailin
    m = Mailin("https://api.sendinblue.com/v2.0","your access key")
	data = { "to" : {"to@example.net":"to whom!"},
		"from" : ["from@email.com", "from email!"],
		"subject" : "My subject",
		"html" : "This is the \<h1>HTML\</h1>",
	}
 
	result = m.send_email(data)
    print(result)
```

When I run this, I get `{u'message': u"valid 'from' email address required", u'code': u'failure', u'data': []}`
When I change it to:
```py
data['from'] = {'from@email.com": 'From Email'}
```
It complains about `json`

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/mailin.py", line 410, in send_email
    return self.post("email",json.dumps(data))
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/mailin.py", line 36, in post
    return self.do_request(resource,"POST",indata)
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/mailin.py", line 30, in do_request
    return response.json()
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/ubuntu/test/env/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The documentation is not consistent with the example with regards to using an array:
to	Email address of the recipient(s). It should be sent as an associative array. Example: array(“to@example.net”=>”to whom”). You can use commas to separate multiple recipients [Mandatory].

from	Email address for From header. It should be sent as an array. Example: array(“from@email.com”,”from email”) [Mandatory].

If someone could point me in the right direction, that would be greatly appreciated.

**Comment by ekta-slit** [comment]
Hello @jayanth1991 

Thank you for contacting us.
The sample provided in the documentation & the same used by you is totally correct.
`
from mailin import Mailin
    m = Mailin("https://api.sendinblue.com/v2.0","your access key")
	data = { "to" : {"to@example.net":"to whom!"},
		"from" : ["from@email.com", "from email!"],
		"subject" : "My subject",
		"html" : "This is the \<h1>HTML\</h1>",
	}
 
    result = m.send_email(data)
    print(result)`

But if you still face the `from` field validation error, please contact our [support team](https://account.sendinblue.com/support) by raising a ticket to look into the issue further.

Regards
SendinBlue Team
