### ISSUE TITLE
Upload to Pypi

### ISSUE THREAD

**Issue by reiven** [mailin-api/mailin-api-python#18]
Hi!

It will be great if this package can be uploaded to Pypi so it can be available in pip to install as a dependency

Thanks!

**Comment by reiven** [comment]
Hi

Actually  trying to install this lib from pip using git repo is failing because it lacks the setup.py file, which is located inside the V1.0 or V2.0 directory.

```python
$ pip install git+https://github.com/mailin-api/mailin-api-python
Downloading/unpacking git+https://github.com/mailin-api/mailin-api-python
  Cloning https://github.com/mailin-api/mailin-api-python to /tmp/pip-XsuXs3-build
  Running setup.py (path:/tmp/pip-XsuXs3-build/setup.py) egg_info for package from git+https://github.com/mailin-api/mailin-api-python
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-XsuXs3-build/setup.py'
```

**Comment by ekta-slit** [comment]
Hello @reiven 

Thanks for contacting us!

To install the package from Pypi, simply use:
` pip install Sendinblue `
Or to upgrade the package use:
` pip install --upgrade Sendinblue `


Regards
SendinBlue Team

**Comment by reiven** [comment]
Thanks @ekta-slit it will be great if the pip package name and this instructions are reflected in the Readme file, as an improvement

**Comment by reiven** [comment]
Thanks @ekta-slit it will be great if the pip package name and this instructions are reflected in the Readme file, as an improvement
