### ISSUE TITLE
Add library to PyPI

### ISSUE THREAD

**Issue by bjmc** [mailin-api/mailin-api-python#19]
Consider adding your library to PyPI to make it easier for users to install. There is a [good tutorial available here.](http://peterdowns.com/posts/first-time-with-pypi.html)

**Comment by n3storm** [comment]
@bjmc  https://pypi.python.org/pypi/Sendinblue

**Comment by bjmc** [comment]
Cool. I didn't find it because I was searching for "mailin-api", thanks!
