### ISSUE TITLE
SendInBlue SSL certificate not verified

### ISSUE THREAD

**Issue by grahamlyons** [mailin-api/mailin-api-python#7]
The commit 1b69eb9d5d7edf421da3ee02b66d21233618719e in issue #3 disabled SSL cert validation by the API. I think that should be reverted and any SSL problems corrected by making sure that the certificate can be properly verified.

**Comment by Nicd** [comment]
This should be done immediately. Currently the library puts customer data at risk.

**Comment by alanhamlett** [comment]
Just use the requests library, it's easier and auto verifies certs.

BTW, I almost signed up for a paid plan today but won't because of this issue.

**Comment by alanhamlett** [comment]
You could also provide actual API docs instead of just a MailIn example. That way we could use the JSON api ourselves and verify the ssl cert.

**Comment by Nicd** [comment]
@alanhamlett API docs are at https://apidocs.sendinblue.com/ -- This library is mostly just a dump of all the API commands and their documentation (copied from PHP as evidenced by many of the comments).

**Comment by alanhamlett** [comment]
@Nicd oh, the curl tab is what I needed. I'll use [requests](https://github.com/kennethreitz/requests) and try out sending.

**Comment by grahamlyons** [comment]
@alanhamlett, the problem wasn't in doing the verification it was that the certificate couldn't be verified - using requests would expose the same issue.

This issue is 2 years old so I have no idea if it's still a problem.
